### Lista de Livros
GET http://localhost:5231/api/livros

###Procurar livro por id
GET http://localhost:5231/api/livros/1

###Procurar livro com id inexistente
GET http://localhost:5231/api/livros/5

### Cadastrar Livro
POST http://localhost:5231/api/livros
Content-Type: application/json

{
    "Titulo": "Crepúsculo",
    "Autor": "e eu vou lembrar?",
    "CategoriaId": 2
}

###Cadastrar livro faltando letras no titulo
POST http://localhost:5231/api/livros
Content-Type: application/json

{
    "Titulo": "aa",
    "Autor": "aaa",
    "CategoriaId": 3
}

###Cadastrar livro com categoria inexistente
POST http://localhost:5231/api/livros
Content-Type: application/json

{
    "Titulo": "aa",
    "Autor": "aaa",
    "CategoriaId": 10
}

###Cadastrar livro faltando letras no autor
POST http://localhost:5231/api/livros
Content-Type: application/json

{
    "Titulo": "aaa",
    "Autor": "aa",
    "CategoriaId": 3
}

### Alterar Livro
PUT http://localhost:5231/api/livros/1
Content-Type: application/json

{
    "Titulo": "1001 Noites",
    "Autor": "Folclore Arábico",
    "CategoriaId": 5
}

### Alterar Livro com id inexistente
PUT http://localhost:5231/api/livros/5
Content-Type: application/json

{
    "Titulo": "1001 Noites",
    "Autor": "Folclore Arábico",
    "CategoriaId": 5
}

### Alterar Livro com categoria invalida
PUT http://localhost:5231/api/livros/1
Content-Type: application/json

{
    "Titulo": "1001 Noites",
    "Autor": "Folclore Arábico",
    "CategoriaId": 10
}

### Alterar Livro com titulo invalido
PUT http://localhost:5231/api/livros/1
Content-Type: application/json

{
    "Titulo": "aa",
    "Autor": "Folclore Arábico",
    "CategoriaId": 5
}

### Alterar Livro com autor invalido
PUT http://localhost:5231/api/livros/1
Content-Type: application/json

{
    "Titulo": "1001 Noites",
    "Autor": "aa",
    "CategoriaId": 5
}

###Deletar livro
DELETE http://localhost:5231/api/livros/4

###Deletar livro com id inexistente
DELETE http://localhost:5231/api/livros/5