### Lista de Livros
GET http://localhost:5231/api/livros

###Procurar livro por id

GET http://localhost:5231/api/livros/1

###Procurar livro com id inexistente
GET http://localhost:5231/api/livros/3

### Cadastrar Livro
POST http://localhost:5231/api/livros
Content-Type: application/json

{
    "Titulo": "Sherlock Holmes",
    "Autor": "Charles Dickens",
    "CategoriaId": 2
}

###Cadastrar livro faltando letras no titulo
POST http://localhost:5231/api/livros
Content-Type: application/json

{
    "Titulo": "aa",
    "Autor": "aaa",
    "CategoriaId": 3
}

###Cadastrar livro com categoria inexistente
POST http://localhost:5231/api/livros
Content-Type: application/json

{
    "Titulo": "aa",
    "Autor": "aaa",
    "CategoriaId": 10
}

###Cadastrar livro faltando letras no autor
POST http://localhost:5231/api/livros
Content-Type: application/json

{
    "Titulo": "aaa",
    "Autor": "aa",
    "CategoriaId": 3
}